"""add_foreign_key_indexes

Revision ID: 0a8c9ff9ad0b
Revises: 007
Create Date: 2026-06-12 21:40:53.786769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a8c9ff9ad0b'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lab_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_lab_progress_user_lab', table_name='lab_progress')
    op.drop_index('ix_lab_progress_user_module', table_name='lab_progress')
    op.create_index(op.f('ix_lab_progress_lab_id'), 'lab_progress', ['lab_id'], unique=False)
    op.create_index(op.f('ix_lab_progress_module_id'), 'lab_progress', ['module_id'], unique=False)
    op.create_index(op.f('ix_lab_progress_section_id'), 'lab_progress', ['section_id'], unique=False)
    op.create_index(op.f('ix_lab_progress_user_id'), 'lab_progress', ['user_id'], unique=False)
    op.alter_column('labs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_labs_module_id'), 'labs', ['module_id'], unique=False)
    op.create_index(op.f('ix_labs_section_id'), 'labs', ['section_id'], unique=False)
    op.alter_column('modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('section_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_section_progress_user_section', table_name='section_progress')
    op.create_index(op.f('ix_section_progress_module_id'), 'section_progress', ['module_id'], unique=False)
    op.create_index(op.f('ix_section_progress_section_id'), 'section_progress', ['section_id'], unique=False)
    op.create_index(op.f('ix_section_progress_user_id'), 'section_progress', ['user_id'], unique=False)
    op.alter_column('sections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_sections_module_id'), 'sections', ['module_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_sections_module_id'), table_name='sections')
    op.alter_column('sections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_section_progress_user_id'), table_name='section_progress')
    op.drop_index(op.f('ix_section_progress_section_id'), table_name='section_progress')
    op.drop_index(op.f('ix_section_progress_module_id'), table_name='section_progress')
    op.create_index('ix_section_progress_user_section', 'section_progress', ['user_id', 'section_id'], unique=True)
    op.alter_column('section_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_labs_section_id'), table_name='labs')
    op.drop_index(op.f('ix_labs_module_id'), table_name='labs')
    op.alter_column('labs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_lab_progress_user_id'), table_name='lab_progress')
    op.drop_index(op.f('ix_lab_progress_section_id'), table_name='lab_progress')
    op.drop_index(op.f('ix_lab_progress_module_id'), table_name='lab_progress')
    op.drop_index(op.f('ix_lab_progress_lab_id'), table_name='lab_progress')
    op.create_index('ix_lab_progress_user_module', 'lab_progress', ['user_id', 'module_id'], unique=False)
    op.create_index('ix_lab_progress_user_lab', 'lab_progress', ['user_id', 'lab_id'], unique=False)
    op.alter_column('lab_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
