"""add_cli_device_auth_table

Revision ID: 229e309db1a1
Revises: c02d1a4944dc
Create Date: 2026-06-23 21:47:58.523637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229e309db1a1'
down_revision: Union[str, None] = 'c02d1a4944dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cli_device_auths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_code', sa.String(length=64), nullable=False),
    sa.Column('user_code', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cli_device_auths_device_code'), 'cli_device_auths', ['device_code'], unique=True)
    op.create_index(op.f('ix_cli_device_auths_user_code'), 'cli_device_auths', ['user_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cli_device_auths_user_code'), table_name='cli_device_auths')
    op.drop_index(op.f('ix_cli_device_auths_device_code'), table_name='cli_device_auths')
    op.drop_table('cli_device_auths')
    # ### end Alembic commands ###
