"""add_total_xp_and_total_sections_to_modules

Revision ID: 60bf8f1c7dff
Revises: 0d8d015dff70
Create Date: 2026-06-23 00:18:58.704533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bf8f1c7dff'
down_revision: Union[str, None] = '0d8d015dff70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('total_xp', sa.Integer(), server_default='0', nullable=False))
    op.add_column('modules', sa.Column('total_sections', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'total_sections')
    op.drop_column('modules', 'total_xp')
    # ### end Alembic commands ###
