"""alter_user_code_length

Revision ID: d8c9fe39fcc5
Revises: 229e309db1a1
Create Date: 2026-06-23 21:51:07.702634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c9fe39fcc5'
down_revision: Union[str, None] = '229e309db1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cli_device_auths', 'user_code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cli_device_auths', 'user_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
